---
jmxUrl: service:jmx:rmi://127.0.0.1/stub/rO0ABXN9AAAAAQAlamF2YXgubWFuYWdlbWVudC5yZW1vdGUucm1pLlJNSVNlcnZlcnhyABdqYXZhLmxhbmcucmVmbGVjdC5Qcm94eeEn2iDMEEPLAgABTAABaHQAJUxqYXZhL2xhbmcvcmVmbGVjdC9JbnZvY2F0aW9uSGFuZGxlcjt4cHNyAC1qYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN0SW52b2NhdGlvbkhhbmRsZXIAAAAAAAAAAgIAAHhyABxqYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN002G0kQxhMx4DAAB4cHdCAAtVbmljYXN0UmVmMgAAF2NzeDIwMDM1LmNhbmxhYi5pYm0uY29tAADXifBwGJMHO0Hz/VJA8gAAAWG6IdpigAEAeA==

whitelistObjectNames:
- com.cognos:type=Metrics,service=*
- java.lang:*

rules:
- pattern: ".*"

